### ISSUE TITLE
Add favicon to index.html

### ISSUE THREAD

**Issue by davebza** [RyanFitzgerald/devportfolio-template#10]
Hi Ryan: firstly, great work on this template.

I'm just wondering if you'd consider adding a favicon to the index.html file? I've added one in a test fork that I've been playing with, and could do a pull request for you if you're interested in it.

**Comment by jonathanGB** [comment]
@RyanFitzgerald +1

**Comment by RyanFitzgerald** [comment]
Thank you! I'm actually hoping to ship the template with a temporary favicon that users can use in the near future; something general enough that it could also be kept if they wanted it.

**Comment by davebza** [comment]
No - that sounds good to me! I'd prefer it your way around, really, as leaving commented code snippets in the main code is messy.

Maybe we could add a section to the README.md on images, with instructions on how to change the favicon if a user wants to? This could go with instructions on how to change the other images as well.

**Comment by RyanFitzgerald** [comment]
Great idea. Right now there really isn't much mention of images in the README, so it makes a lot of sense to have an additional section dedicated specifically to all the images used on the page (main background, project image placeholders, and favicon) and how they should / can be changed up.

**Comment by RyanFitzgerald** [comment]
I've gone ahead and added both an images section to the README and a default favicon to the page. If that properly addresses what you were looking for let me know and I'll close this!

**Comment by crivotz** [comment]
Hi Ryan,
first of all thanks for the project.

I added to my fork the following code that I usualy use for basic webpage

``` html
<meta name="mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-capable" content="yes">
<link rel="apple-touch-icon" href="images/favicon/favicon.png">
<link rel="icon" href="images/favicon/favicon.png">
<!--[if IE]><link rel="shortcut icon" href="images/favicon/favicon.ico"><![endif]-->
<!-- or, set /favicon.ico for IE10 win -->
```

If you need a 'default' favicon you can use [this](https://goo.gl/E2asnA). I made for an old dead project and seems that it's perfect for your template style

**Comment by RyanFitzgerald** [comment]
Going to close this issue for now, as the template does have a basic favicon that can be kept or changed at this point.
