### ISSUE TITLE
Make the navigation bar sticky

### ISSUE THREAD

**Issue by sahildua2305** [RyanFitzgerald/devportfolio-template#13]

**Comment by jonathanGB** [comment]
+1 @RyanFitzgerald

**Comment by RyanFitzgerald** [comment]
Added in 1.1.3, thanks for the suggestion!

**Comment by sahildua2305** [comment]
@RyanFitzgerald I think it's a good idea to update the demo as well so as to reflect accurately.

**Comment by RyanFitzgerald** [comment]
I decided to leave it out of the original demo because it was a default feature, rather an optional one, but I'll more than likely be creating an additional demo that has all the optional features on by default.

**Comment by sahildua2305** [comment]
@RyanFitzgerald fair enough! 👍
