### ISSUE TITLE
Add "See More" to the projects Section

### ISSUE THREAD

**Issue by shrobon** [RyanFitzgerald/devportfolio-template#14]
Adding a "See-More" to the projects section would be a great idea.
You could then prioritize your projects keeping the best ones on the top while the projects little lower in importance can be loaded when clicking see-more.

**Comment by RyanFitzgerald** [comment]
Good idea! I'm going to try and work this into one of the next releases as an optional feature for those who want to list lots of projects.

**Comment by RyanFitzgerald** [comment]
Added in release 1.2.0, thanks for feedback!
