### ISSUE TITLE
New navigationbar/menu options

### ISSUE THREAD

**Issue by thelaith** [RyanFitzgerald/devportfolio-template#18]
While I very much love your theme, it's a shame it's ruined by such a boring navigation bar - I wish there was the option to choose between more modern navbar options, like the one Grayscale has: https://startbootstrap.com/template-overviews/grayscale/

**Comment by RyanFitzgerald** [comment]
Thanks for the feedback! I'll look into adding another optional header style for those that don't like the default one, I appreciate the feedback.
