### ISSUE TITLE
Where's your copyright? :(

### ISSUE THREAD

**Issue by PunKeel** [RyanFitzgerald/devportfolio-template#2]
Hello there,
This template looks neat!

The MIT license requires users (us) to give you credit.

> Conditions: License and copyright notice

I haven't seen your name anywhere in your demo's source-code.
How would you like to be thanked? :-) imo it's possible to have minified files with a copyright header, would this be _enough_?

Cheers!

**Comment by RyanFitzgerald** [comment]
Thanks! Sorry about the confusion regarding the license and copyright. I've pushed a change that preserves the top comment in the JS/CSS and I added a bit of info in there. That's more than enough for me as far as credit goes. Hope that clears it up!
