### ISSUE TITLE
Adding a 404 page

### ISSUE THREAD

**Issue by thelaith** [RyanFitzgerald/devportfolio-template#21]
Hi

I know it might be a bit much to ask, but a 404 page with that simple, nice way you code would be nice as well for this portfolio site, in case you have time.

**Comment by RyanFitzgerald** [comment]
Thanks for the suggestion, but I don't think I will be adding a 404 page at this point since it's primarily meant to be a single-page template. I will however reopen this issue if I end up adding additional pages (i.e. project pages) to the template and readdress it then.
