### ISSUE TITLE
Section adding

### ISSUE THREAD

**Issue by n1c0x** [RyanFitzgerald/devportfolio-template#24]
Hello, 

Great template, I like it. 

It would be great if a user could add new sections, for languages or other important informations (hobbies, certifications or trainings for example)

**Comment by RyanFitzgerald** [comment]
Great idea! I'm definitely going to add some additional optional sections like these to the next release.

**Comment by RyanFitzgerald** [comment]
Added in release 1.2.0, thanks for the feedback!

**Comment by n1c0x** [comment]
Great work, thanks 👍
