### ISSUE TITLE
Project Images

### ISSUE THREAD

**Issue by jasonbunnell** [RyanFitzgerald/devportfolio-template#25]
I forked this project and have it up and running on jasonbunnell.com.  I am having trouble with the **project images**.  I was able to change the project.jpg image.  When I attempted to use my-own-image.jpg it did not conform to the formating.  I tried changing:
```
.project-image {
    float: left;
    max-width: 300px; 
```
Thoughts?

**Comment by RyanFitzgerald** [comment]
Hi,

What happened with the images? If you use 300x300 images and simply replace the img src with your new images, it shouldn't have any issues and you shouldn't need to add additional CSS. I tried taking a look on your site but it seems you've gone back to the placeholders.

Let me know,

Ryan

**Comment by jasonbunnell** [comment]
Changing the img src with a 300 x 300 pixel image fixed the issue.  I thought I had checked that.  Thanks for the help.  By the way, impressed with your site.  What theme do you use for you blog?  The devportfolio-template is great, too.  Great design.  Thanks!

**Comment by RyanFitzgerald** [comment]
Glad you got it working and thanks for positive feedback! For the blog I actually created my own theme, but I'm hoping to release it in the next couple week to compliment this portfolio theme, I just have a couple tweaks to do.
