### ISSUE TITLE
Removing Project Image Bug

### ISSUE THREAD

**Issue by omaarr90** [RyanFitzgerald/devportfolio-template#30]
Nice job, 

The issue is that when I remove the project image, the whole project div is removed. somehow the height of that div is related to the image height. 

Expcted behavior,

when removing the image div, content should be left aligned and div expand to fill the content

**Comment by RyanFitzgerald** [comment]
Good catch! I'll get something together to have that fixed.

Cheers,

Ryan

**Comment by RyanFitzgerald** [comment]
Added in release 1.2.1, thanks again for the feedback!

**Comment by omaarr90** [comment]
Thank you for your prompt response.
