### ISSUE TITLE
Google PageSpeed recommendations should be followed

### ISSUE THREAD

**Issue by incyclum** [RyanFitzgerald/devportfolio-template#9]
See https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fryanfitzgerald.github.io%2Fdevportfolio-template%2F&tab=mobile

**Comment by RyanFitzgerald** [comment]
In this case, arguably the most important PageSpeed recommendations are followed (minification, page response time, compression, etc.) and the remaining warnings are something that would be handled on an individual basis by each user should they wish to address it on their end (i.e. caching). Also, the images are meant to serve as placeholders that get replaced by user content, so I'm not overly concerned with them being able to be reduced slightly.
